/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef PKG_DEPENDENCY_PRIVATE_BAKE_CONFIG_H
#define PKG_DEPENDENCY_PRIVATE_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Headers of private dependencies */
#ifdef PKG_DEPENDENCY_PRIVATE_IMPL
#include <pkg_helloworld>
#endif

/* Convenience macro for exporting symbols */
#if PKG_DEPENDENCY_PRIVATE_IMPL && defined _MSC_VER
#define PKG_DEPENDENCY_PRIVATE_EXPORT __declspec(dllexport)
#elif PKG_DEPENDENCY_PRIVATE_IMPL
#define PKG_DEPENDENCY_PRIVATE_EXPORT __attribute__((__visibility__("default")))
#elif defined _MSC_VER
#define PKG_DEPENDENCY_PRIVATE_EXPORT __declspec(dllimport)
#else
#define PKG_DEPENDENCY_PRIVATE_EXPORT
#endif

#endif

